import { describe, expect, it, vi } from "vitest";
import { CALLBACK_MAX_SECONDS, beginUpload, claimUploadStatus, handoffAfterClaim, patchSessionAfterUpload, reserveSession, scheduledJobs, statusObjectKey, uploadObjectKey, validateCallback, type DirectUploadAdapter, type SessionPatchAdapter } from "@/lib/cloudflare-upload-contract";
const s="abcdefghijklmnopqrst", u="11111111-1111-4111-8111-111111111111", path=uploadObjectKey(s,u);
const adapter=(cas:"applied"|"conflict"="applied"):DirectUploadAdapter=>({authorizeUpload:vi.fn(async()=>({uploadUrl:"https://example.invalid",expiresAt:1})),compareAndSet:vi.fn(async()=>cas),enqueueExtraction:vi.fn(async()=>{})});
const auth=(allowed=true)=>({canEdit:vi.fn(async()=>allowed),getSession:vi.fn(async()=>({id:s,acceptsPdf:true}))});
describe("Cloudflare direct-upload parity contract",()=>{
 it("authorizes editor and authoritative session before signing",async()=>{const a=adapter(), x=auth(); await expect(beginUpload(a,x,{sessionId:s,uploadId:u,origin:"https://app",expectedOrigin:"https://app",pathname:path,statusPath:statusObjectKey(s,u)})).resolves.toBeTruthy(); await expect(beginUpload(a,auth(false),{sessionId:s,uploadId:u,origin:"https://app",expectedOrigin:"https://app",pathname:path,statusPath:statusObjectKey(s,u)})).rejects.toThrow("editor_inactive");});
 it("rejects a self-consistent callback from another session",()=>expect(()=>validateCallback({sessionId:s,uploadId:u},{sessionId:"other",uploadId:u,pathname:uploadObjectKey("other",u)})).toThrow("upload_path_mismatch"));
 it("uses session-specific CAS for winner loser replay",async()=>{const win=adapter(); await expect(claimUploadStatus(win,{sessionId:s,uploadId:u},{value:{status:"pending"},version:"1"})).resolves.toBe("claimed"); expect(vi.mocked(win.compareAndSet)).toHaveBeenCalledWith(`upload-status:${s}:${u}`,"1",{status:"processing"}); await expect(claimUploadStatus(adapter("conflict"),{sessionId:s,uploadId:u},{value:{status:"pending"},version:"1"})).resolves.toBe("conflict"); await expect(claimUploadStatus(adapter(),{sessionId:s,uploadId:u},{value:{status:"complete"},version:"1"})).resolves.toBe("replay");});
 it("isolates session reservations",async()=>{const a=adapter(); await reserveSession(a,s,{value:{},version:"1"},u); await reserveSession(a,"other",{value:{},version:"1"},u); expect(vi.mocked(a.compareAndSet)).toHaveBeenNthCalledWith(1,`session:${s}`,"1",{sourceUploadId:u}); expect(vi.mocked(a.compareAndSet)).toHaveBeenNthCalledWith(2,"session:other","1",{sourceUploadId:u});});
 it("patches supplied session fields with bounded CAS retry and reports exhaustion",async()=>{let reads=0; const preserving:SessionPatchAdapter={readSession:vi.fn(async()=>({value:{keep:"value",nested:{safe:true}},version:String(++reads)})),compareAndSet:vi.fn(async(_k,_v,value)=>reads===1?"conflict" as const:"applied" as const)}; await expect(patchSessionAfterUpload(preserving,s,u)).resolves.toBe("patched"); expect(vi.mocked(preserving.compareAndSet)).toHaveBeenLastCalledWith(`session:${s}`,"2",{keep:"value",nested:{safe:true},sourceUploadId:u}); const exhausted:SessionPatchAdapter={readSession:vi.fn(async()=>({value:{keep:"value"},version:"1"})),compareAndSet:vi.fn(async()=>"conflict" as const)}; await expect(patchSessionAfterUpload(exhausted,s,u,2)).resolves.toBe("conflict"); expect(vi.mocked(exhausted.compareAndSet)).toHaveBeenCalledTimes(2);});
 it("queues post-claim work within the callback budget",async()=>{const a=adapter(); await handoffAfterClaim(a,{sessionId:s,uploadId:u},CALLBACK_MAX_SECONDS); expect(a.enqueueExtraction).toHaveBeenCalled(); await expect(handoffAfterClaim(a,{sessionId:s,uploadId:u},301)).rejects.toThrow("callback_duration_exceeded");});
 it("preserves exact scheduled reconciliation mapping",()=>expect(scheduledJobs).toEqual([{name:"upload-cleanup",cron:"*/15 * * * *"},{name:"lead-reconciliation",cron:"*/5 * * * *"},{name:"trace-cleanup",cron:"17 3 * * *"}]));
});
