import { describe, expect, it } from "vitest";
import { CloudflareR2D1MigrationDestination, VercelBlobReadAdapter } from "./provider-migration-adapters";
import type { D1Database, R2Bucket } from "./types";

const stream = (value: string) => new ReadableStream<Uint8Array>({ start(c) { c.enqueue(new TextEncoder().encode(value)); c.close(); } });
describe("provider migration adapters", () => {
  it("paginates private Vercel Blob data and verifies byte size", async () => { let cursor: string | undefined; const client = { async list(input: { cursor?: string }) { cursor = input.cursor; return input.cursor ? { blobs: [{ pathname: "try-me/leads/abcdefghijklmnopqrst.json", size: 2, url: "private" }], hasMore: false } : { blobs: [{ pathname: "try-me/sessions/abcdefghijklmnopqrst.json", size: 2, url: "private" }], cursor: "opaque", hasMore: true }; }, async get() { return { statusCode: 200, stream: stream("{}") }; } }; const source = new VercelBlobReadAdapter(client); const first = await source.list(); const second = await source.list("opaque"); expect(first.objects).toHaveLength(1); expect(second.objects).toHaveLength(1); expect(cursor).toBe("opaque"); expect([...await (async () => { const out: Uint8Array[] = []; for await (const c of await source.read(first.objects[0]!)) out.push(c); return out; })()]).toHaveLength(1); });
  it("sanitizes private auth and byte failures", async () => { const denied = new VercelBlobReadAdapter({ async list() { throw new Error("401 private-token"); }, async get() { return null; } }); await expect(denied.list()).rejects.toThrow("source_auth_failed"); const mismatch = new VercelBlobReadAdapter({ async list() { return { blobs: [] }; }, async get() { return { statusCode: 200, stream: stream("x") }; } }); await expect(mismatch.read({ key: "try-me/sessions/abcdefghijklmnopqrst.json", size: 2, cursor: "x" })).rejects.toThrow("source_size_mismatch"); });
  it("uses exact-match, token-owned receipt batch semantics instead of result counts", async () => { const rows = new Map<string, { ownership: "created" | "preexisting" }>(), sqls: string[] = []; let batchResult = [{ success: true, meta: { changes: 0 } }, { success: true, meta: { changes: 1 } }], allowReceipt = true; const db = { prepare(sql: string) { sqls.push(sql); return { bind(...values: unknown[]) { return { async first() { return rows.get(String(values[1])) ?? null; }, async run() { return { success: true, meta: { changes: 1 } }; } }; } }; }, async batch(statements: unknown[]) { void statements; if (allowReceipt) rows.set("d".repeat(64), { ownership: "created" }); return batchResult; } } as unknown as D1Database; const r2 = { async head() { return null; }, async put() { return { key: "x", etag: "e", size: 2 }; }, async createMultipartUpload() { return { uploadId: "x" }; } } as R2Bucket; const adapter = new CloudflareR2D1MigrationDestination(r2, db); const input = { sourceIdentity: "private", sourceIdentityHash: "a".repeat(64), kind: "session" as const, destinationKey: "private", sha256: "b".repeat(64), bytes: 2, ownershipToken: "c".repeat(64), receiptRef: "d".repeat(64) }; expect(await adapter.putMappingIfAbsent(input)).toMatchObject({ ownership: "created" }); expect(sqls.some((sql) => sql.includes("created_run_token") && sql.includes("CASE WHEN") && sql.includes("sha256 = ?"))).toBe(true); rows.clear(); allowReceipt = false; batchResult = [{ success: true, meta: { changes: 1 } }, { success: true, meta: { changes: 0 } }]; expect(await adapter.putMappingIfAbsent(input)).toBe("conflict"); });
  it("treats malformed batch output and durable preexisting receipt safely", async () => { const rows = new Map<string, { ownership: "created" | "preexisting" }>(); const db = { prepare() { return { bind(...values: unknown[]) { return { async first() { return rows.get(String(values[1])) ?? null; }, async run() { return { success: true, meta: { changes: 1 } }; } }; } }; }, async batch() { return [{ success: false, meta: { changes: 1 } }]; } } as unknown as D1Database; const r2 = { async head() { return null; }, async createMultipartUpload() { return { uploadId: "x" }; } } as R2Bucket; const adapter = new CloudflareR2D1MigrationDestination(r2, db); const input = { sourceIdentity: "private", sourceIdentityHash: "a".repeat(64), kind: "session" as const, destinationKey: "private", sha256: "b".repeat(64), bytes: 2, ownershipToken: "c".repeat(64), receiptRef: "d".repeat(64) }; await expect(adapter.putMappingIfAbsent(input)).rejects.toThrow("migration_failed"); rows.set(input.receiptRef, { ownership: "preexisting" }); expect(await adapter.putMappingIfAbsent(input)).toMatchObject({ ownership: "preexisting" }); });
});
