import { createHash } from "node:crypto";
import type { D1Database, R2Bucket } from "@/lib/cloudflare-runtime/types";
import type { BlobObject, OwnershipReceipt, ReadOnlyBlobSource, WriteOnceDestination } from "@/lib/cloudflare-runtime/vercel-blob-migration";

type VercelBlob = { pathname: string; size: number; url: string; contentType?: string; etag?: string };
export interface VercelBlobClient { list(input: { prefix: string; cursor?: string; token?: string }): Promise<{ blobs: VercelBlob[]; cursor?: string; hasMore?: boolean }>; get(pathname: string, input: { access: "private"; token?: string; useCache: false }): Promise<{ statusCode: number; stream: ReadableStream<Uint8Array> } | null>; }
const safe = (error: unknown) => error instanceof Error && /^(?:source_auth_failed|source_read_failed|source_list_failed|source_size_mismatch)$/.test(error.message) ? error.message : "source_read_failed";
const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const bytes = async (stream: ReadableStream<Uint8Array>) => { const reader = stream.getReader(); const chunks: Uint8Array[] = []; let size = 0; for (;;) { const next = await reader.read(); if (next.done) break; size += next.value.byteLength; chunks.push(next.value); } const out = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { out.set(chunk, offset); offset += chunk.byteLength; } return out; };

/** Concrete private Vercel Blob adapter. Token is supplied by the manual CLI only. */
export class VercelBlobReadAdapter implements ReadOnlyBlobSource {
  constructor(private readonly client: VercelBlobClient, private readonly token?: string, private readonly prefix = "try-me/") {}
  async snapshot() { return { id: sha(`vercel-blob:${this.prefix}`), digest: sha(`vercel-blob-manual-snapshot:${this.prefix}`) }; }
  async list(cursor?: string) { try { const page = await this.client.list({ prefix: this.prefix, cursor, token: this.token }); return { objects: page.blobs.map((blob) => ({ key: blob.pathname, size: blob.size, etag: blob.etag, contentType: blob.contentType, cursor: sha(cursor ?? "first") })), nextCursor: page.hasMore ? page.cursor : undefined }; } catch (error) { throw new Error(String(error).includes("401") || String(error).includes("403") ? "source_auth_failed" : "source_list_failed"); } }
  async read(object: BlobObject) { try { const result = await this.client.get(object.key, { access: "private", token: this.token, useCache: false }); if (!result || result.statusCode !== 200) throw new Error("source_read_failed"); const body = await bytes(result.stream); if (body.byteLength !== object.size) throw new Error("source_size_mismatch"); return (async function* () { yield body; })(); } catch (error) { throw new Error(safe(error)); } }
}

const receipt = (ref: string, ownership: "created" | "preexisting"): OwnershipReceipt => ({ receiptRef: ref, ownership });
/** R2 object writes plus D1-owned mapping receipts. Inert until separately instantiated by the CLI. */
export class CloudflareR2D1MigrationDestination implements WriteOnceDestination {
  constructor(private readonly r2: R2Bucket, private readonly db: D1Database) {}
  async lookupObjectReceipt({ ownershipToken, receiptRef }: { ownershipToken: string; receiptRef: string }) { const row = await this.db.prepare("SELECT ownership FROM cf_migration_object_receipts WHERE run_token = ? AND receipt_ref = ?").bind(ownershipToken, receiptRef).first<{ ownership: "created" | "preexisting" }>(); return row ? receipt(receiptRef, row.ownership) : null; }
  async lookupMappingReceipt({ ownershipToken, receiptRef }: { ownershipToken: string; receiptRef: string }) { const row = await this.db.prepare("SELECT ownership FROM cf_migration_mapping_receipts WHERE run_token = ? AND receipt_ref = ?").bind(ownershipToken, receiptRef).first<{ ownership: "created" | "preexisting" }>(); return row ? receipt(receiptRef, row.ownership) : null; }
  async putIfAbsent(input: Parameters<WriteOnceDestination["putIfAbsent"]>[0]) { const existing = await this.lookupObjectReceipt(input); if (existing) return existing; if (!this.r2.put) throw new Error("migration_failed"); const head = await this.r2.head(input.key); if (head) { if (head.size !== input.body.byteLength || head.httpMetadata?.contentType !== input.contentType) return "conflict" as const; await this.db.prepare("INSERT OR IGNORE INTO cf_migration_object_receipts (run_token, receipt_ref, ownership) VALUES (?, ?, 'preexisting')").bind(input.ownershipToken, input.receiptRef).run(); return receipt(input.receiptRef, "preexisting"); }
    await this.r2.put(input.key, input.body, { httpMetadata: { contentType: input.contentType }, customMetadata: { sha256: input.sha256 } }); await this.db.prepare("INSERT OR IGNORE INTO cf_migration_object_receipts (run_token, receipt_ref, ownership) VALUES (?, ?, 'created')").bind(input.ownershipToken, input.receiptRef).run(); return receipt(input.receiptRef, "created"); }
  async putMappingIfAbsent(input: Parameters<WriteOnceDestination["putMappingIfAbsent"]>[0]) { const existing = await this.lookupMappingReceipt(input); if (existing) return existing; if (!this.db.batch) throw new Error("migration_failed"); const mapping = this.db.prepare("INSERT OR IGNORE INTO cf_migration_mappings (source_identity_hash, destination_ref, sha256, bytes, kind) VALUES (?, ?, ?, ?, ?)").bind(input.sourceIdentityHash, sha(`destination:${input.sourceIdentityHash}`), input.sha256, input.bytes, input.kind); const receiptInsert = this.db.prepare("INSERT OR IGNORE INTO cf_migration_mapping_receipts (run_token, receipt_ref, ownership) VALUES (?, ?, 'created')").bind(input.ownershipToken, input.receiptRef); const result = await this.db.batch([mapping, receiptInsert]); if ((result[1]?.meta?.changes ?? 0) !== 1) return "conflict" as const; return receipt(input.receiptRef, "created"); }
}
