import { describe, expect, it } from "vitest";
import { CloudflareR2D1MigrationDestination, VercelBlobReadAdapter } from "./provider-migration-adapters";
import type { D1Database, R2Bucket } from "./types";

const stream = (value: string) => new ReadableStream<Uint8Array>({ start(c) { c.enqueue(new TextEncoder().encode(value)); c.close(); } });
describe("provider migration adapters", () => {
  it("paginates private Vercel Blob data and verifies byte size", async () => { let cursor: string | undefined; const client = { async list(input: { cursor?: string }) { cursor = input.cursor; return input.cursor ? { blobs: [{ pathname: "try-me/leads/abcdefghijklmnopqrst.json", size: 2, url: "private" }], hasMore: false } : { blobs: [{ pathname: "try-me/sessions/abcdefghijklmnopqrst.json", size: 2, url: "private" }], cursor: "opaque", hasMore: true }; }, async get() { return { statusCode: 200, stream: stream("{}") }; } }; const source = new VercelBlobReadAdapter(client); const first = await source.list(); const second = await source.list("opaque"); expect(first.objects).toHaveLength(1); expect(second.objects).toHaveLength(1); expect(cursor).toBe("opaque"); expect([...await (async () => { const out: Uint8Array[] = []; for await (const c of await source.read(first.objects[0]!)) out.push(c); return out; })()]).toHaveLength(1); });
  it("sanitizes private auth and byte failures", async () => { const denied = new VercelBlobReadAdapter({ async list() { throw new Error("401 private-token"); }, async get() { return null; } }); await expect(denied.list()).rejects.toThrow("source_auth_failed"); const mismatch = new VercelBlobReadAdapter({ async list() { return { blobs: [] }; }, async get() { return { statusCode: 200, stream: stream("x") }; } }); await expect(mismatch.read({ key: "try-me/sessions/abcdefghijklmnopqrst.json", size: 2, cursor: "x" })).rejects.toThrow("source_size_mismatch"); });
  it("uses receipt lookups and atomic mapping batches", async () => { const rows = new Map<string, { ownership: "created" | "preexisting" }>(), batches: unknown[][] = []; const db = { prepare(sql: string) { void sql; return { bind(...values: unknown[]) { return { async first() { return rows.get(String(values[1])) ?? null; }, async run() { rows.set(String(values[1]), { ownership: "created" }); return { success: true, meta: { changes: 1 } }; } }; } }; }, async batch(statements: unknown[]) { batches.push(statements); return [{ success: true, meta: { changes: 1 } }, { success: true, meta: { changes: 1 } }]; } } as unknown as D1Database; const r2 = { async head() { return null; }, async put() { return { key: "x", etag: "e", size: 2 }; }, async createMultipartUpload() { return { uploadId: "x" }; } } as R2Bucket; const adapter = new CloudflareR2D1MigrationDestination(r2, db); const result = await adapter.putMappingIfAbsent({ sourceIdentity: "private", sourceIdentityHash: "a".repeat(64), kind: "session", destinationKey: "private", sha256: "b".repeat(64), bytes: 2, ownershipToken: "c".repeat(64), receiptRef: "d".repeat(64) }); expect(result).toMatchObject({ ownership: "created" }); expect(batches).toHaveLength(1); });
});
