import { describe, expect, it } from "vitest";
import { CALLBACK_LEASE_MS, CAPABILITY_TTL_MS, MAX_PDF_BYTES, MockRuntime, SCHEDULED_HANDLERS, objectKey, statusKey } from "@/lib/cloudflare-runtime/upload-runtime";

const identity = { sessionId: "session-a", uploadId: "upload-a" };
const head = (id = identity) => ({ key: objectKey(id.sessionId, id.uploadId), etag: "etag-1", size: 42, contentType: "application/pdf" });
const ready = (runtime = new MockRuntime(), now = 1) => { runtime.seedSession(identity.sessionId, { unrelated: "kept" }); const cap = runtime.issue({ ...identity, nonce: "cap-a", now }); runtime.putDirect(cap.nonce, head(), now); return { runtime, cap, now }; };

describe("inactive Cloudflare upload runtime proof", () => {
  it("issues exact expiring write-once PDF capabilities with the live max", () => { const runtime = new MockRuntime(99); const cap = runtime.issue({ ...identity, nonce: "cap", now: 10 }); expect(cap).toMatchObject({ objectKey: objectKey(identity.sessionId, identity.uploadId), statusKey: statusKey(identity.sessionId, identity.uploadId), mime: "application/pdf", maxBytes: 99, expiresAt: 10 + CAPABILITY_TTL_MS, writeOnce: true }); expect(() => runtime.issue({ ...identity, nonce: "cap", now: 10 })).toThrow("capability_exists"); });
  it("never reissues an existing pending, complete, or failed upload identity", async () => { const pending = new MockRuntime(); pending.issue({ ...identity, nonce: "p", now: 1 }); expect(() => pending.issue({ ...identity, nonce: "p2", now: 2 })).toThrow("upload_identity_exists"); const complete = ready(); await complete.runtime.claimReserveAndEnqueue(complete.cap.nonce, "owner", complete.now); complete.runtime.processQueue(`extract:${identity.sessionId}:${identity.uploadId}`, "success", "owner"); expect(() => complete.runtime.issue({ ...identity, nonce: "c2", now: 2 })).toThrow("upload_identity_exists"); const failed = ready(); await failed.runtime.claimReserveAndEnqueue(failed.cap.nonce, "owner", failed.now); failed.runtime.processQueue(`extract:${identity.sessionId}:${identity.uploadId}`, "retry", "owner", 1); expect(() => failed.runtime.issue({ ...identity, nonce: "f2", now: 2 })).toThrow("upload_identity_exists"); });
  it("rejects forged, expired, cross-session, overwrite, wrong ETag/type, and size metadata", async () => { const { runtime, cap, now } = ready(); expect(() => runtime.putDirect(cap.nonce, { ...head(), key: "forged", }, now)).toThrow("invalid_upload_object"); expect(() => runtime.putDirect(cap.nonce, { ...head(), contentType: "text/plain" }, now)).toThrow("invalid_upload_object"); expect(() => runtime.putDirect(cap.nonce, { ...head(), size: MAX_PDF_BYTES + 1 }, now)).toThrow("invalid_upload_object"); expect(() => runtime.putDirect(cap.nonce, { ...head(), etag: "" }, now)).toThrow("invalid_upload_object"); await expect(runtime.callback(cap.nonce, "a", now + CAPABILITY_TTL_MS)).rejects.toThrow("capability_expired"); const other = runtime.issue({ sessionId: "other", uploadId: identity.uploadId, nonce: "other", now }); runtime.putDirect(other.nonce, head({ sessionId: "other", uploadId: identity.uploadId }), now); await expect(runtime.callback(other.nonce, "a", now)).resolves.toBe("claimed"); expect(() => runtime.putDirect(cap.nonce, head(), now)).toThrow("invalid_upload_object"); });
  it("preserves unrelated fields and retries bounded session CAS conflicts", async () => { const { runtime } = ready(); runtime.forceSessionConflicts(2); await expect(runtime.reserveSession(identity)).resolves.toBe("reserved"); expect(runtime.sessions.get("session:session-a")?.value).toEqual({ unrelated: "kept", sourceUploadId: identity.uploadId }); runtime.forceSessionConflicts(3); await expect(runtime.reserveSession({ ...identity, uploadId: "other" })).resolves.toBe("conflict"); });
  it("has one concurrent winner, rejects old owners, and reclaims stale leases", async () => { const { runtime, cap, now } = ready(); await expect(runtime.callback(cap.nonce, "first", now)).resolves.toBe("claimed"); await expect(runtime.callback(cap.nonce, "second", now + 1)).resolves.toBe("in-progress"); expect(() => runtime.completeOwned(cap.statusKey, "second")).toThrow("owner_lost"); await expect(runtime.callback(cap.nonce, "second", now + CALLBACK_LEASE_MS + 1)).resolves.toBe("claimed"); expect(runtime.states.get(cap.statusKey)?.attempts).toBe(2); });
  it("releases owned state/session if queue handoff fails and deduplicates queue messages", async () => { const { runtime, cap, now } = ready(); runtime.failEnqueue = true; await expect(runtime.claimReserveAndEnqueue(cap.nonce, "owner", now)).rejects.toThrow("enqueue_failed"); expect(runtime.states.get(cap.statusKey)?.status).toBe("pending"); expect(runtime.sessions.get("session:session-a")?.value.sourceUploadId).toBeUndefined(); runtime.failEnqueue = false; await runtime.claimReserveAndEnqueue(cap.nonce, "owner", now + 1); runtime.enqueue(cap); expect(runtime.queue.size).toBe(1); });
  it("handles duplicate queue delivery, DLQ terminal state, and records D1 only after owned completion", async () => { const { runtime, cap, now } = ready(); await runtime.claimReserveAndEnqueue(cap.nonce, "owner", now); const id = `extract:${identity.sessionId}:${identity.uploadId}`; expect(runtime.processQueue(id, "retry", "owner", 1)).toBe("dlq"); expect(runtime.states.get(cap.statusKey)?.status).toBe("failed"); expect(runtime.outcomes).toEqual([`d1:failed:${cap.statusKey}`]); expect(runtime.processQueue(id, "success", "owner")).toBe("duplicate"); const second = ready(new MockRuntime(), 10); await second.runtime.claimReserveAndEnqueue(second.cap.nonce, "owner", 10); second.runtime.processQueue(`extract:${identity.sessionId}:${identity.uploadId}`, "success", "owner"); expect(second.runtime.states.get(second.cap.statusKey)?.status).toBe("complete"); expect(second.runtime.outcomes).toEqual([`d1:complete:${second.cap.statusKey}`]); });
  it("dispatches exactly the three existing schedules", () => { const runtime = new MockRuntime(); for (const job of SCHEDULED_HANDLERS) runtime.dispatchScheduled(job.name); expect(runtime.cronDispatches).toEqual(SCHEDULED_HANDLERS.map((job) => job.name)); });
});
