import { describe, expect, it } from "vitest";
import { migrateBlobSnapshot, type BlobObject, type MigrationCheckpoint, type ReadOnlyBlobSource, type WriteOnceDestination } from "./vercel-blob-migration";
const enc = new TextEncoder(), id = "abcdefghijklmnopqrst", key = `try-me/sessions/${id}.json`, digest = "a".repeat(64);
const object: BlobObject = { key, size: 2, cursor: "private-cursor", contentType: "application/json" };
const source = (): ReadOnlyBlobSource => ({ async snapshot() { return { id: "private-snapshot", digest }; }, async list(cursor) { return cursor ? { objects: [] } : { objects: [object] }; }, async read() { return (async function* () { yield enc.encode("{}"); })(); } });
const store = () => ({ value: null as MigrationCheckpoint | null, async load() { return this.value; }, async save(value: MigrationCheckpoint) { this.value = structuredClone(value); } });
function destination() { const objects = new Map<string, import("./vercel-blob-migration").OwnershipReceipt>(), mappings = new Map<string, import("./vercel-blob-migration").OwnershipReceipt>(); const receipt = (ref: string, ownership: "created" | "preexisting") => ({ receiptRef: ref, ownership } as const); const adapter: WriteOnceDestination = { async lookupObjectReceipt({ receiptRef }) { return objects.get(receiptRef) ?? null; }, async putIfAbsent({ receiptRef }) { const current = objects.get(receiptRef); if (current) return current; const next = receipt(receiptRef, "created"); objects.set(receiptRef, next); return next; }, async lookupMappingReceipt({ receiptRef }) { return mappings.get(receiptRef) ?? null; }, async putMappingIfAbsent({ receiptRef }) { const current = mappings.get(receiptRef); if (current) return current; const next = receipt(receiptRef, "created"); mappings.set(receiptRef, next); return next; } }; return { adapter, objects, mappings, receipt }; }
describe("durable ownership receipts", () => {
  it("persists no raw key/cursor and rolls back created receipts", async () => { const s = store(), d = destination(); const report = await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); expect(report).toMatchObject({ reconciled: true, rollback: [{ objectCreated: true, mappingCreated: true }] }); const json = JSON.stringify(s.value); expect(json).not.toContain(key); expect(json).not.toContain(id); expect(json).not.toContain("private-cursor"); });
  it("excludes preexisting object after a crash and retry", async () => { const s = store(), d = destination(); const original = d.adapter.putIfAbsent; d.adapter.putIfAbsent = async (input) => { const r = d.receipt(input.receiptRef, "preexisting"); d.objects.set(input.receiptRef, r); throw new Error("crash"); }; await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); d.adapter.putIfAbsent = original; const report = await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); expect(report.rollback).toEqual([{ sourceIdentityHash: expect.any(String), destinationRef: expect.any(String), objectCreated: false, mappingCreated: true }]); });
  it("recovers inserted object receipt after crash before checkpoint", async () => { const s = store(), d = destination(); let crash = true; const original = d.adapter.putIfAbsent; d.adapter.putIfAbsent = async (input) => { const r = await original(input); if (crash) { crash = false; throw new Error("crash"); } return r; }; await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); d.adapter.putIfAbsent = original; const report = await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); expect(report.rollback[0]).toMatchObject({ objectCreated: true, mappingCreated: true }); });
  it("recovers inserted mapping receipt after crash before mapped checkpoint", async () => { const s = store(), d = destination(); let crash = true; const original = d.adapter.putMappingIfAbsent; d.adapter.putMappingIfAbsent = async (input) => { const r = await original(input); if (crash) { crash = false; throw new Error("crash"); } return r; }; await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); d.adapter.putMappingIfAbsent = original; const report = await migrateBlobSnapshot(source(), d.adapter, { dryRun: false, checkpoint: s }); expect(report.rollback[0]).toMatchObject({ objectCreated: true, mappingCreated: true }); });
  it("fails closed for concurrent conflict and corrupt/mismatched receipt", async () => { const d = destination(); d.adapter.putIfAbsent = async () => "conflict"; expect((await migrateBlobSnapshot(source(), d.adapter, { dryRun: false })).reconciled).toBe(false); const bad = destination(); bad.adapter.putIfAbsent = async () => ({ receiptRef: "b".repeat(64), ownership: "created" }); expect((await migrateBlobSnapshot(source(), bad.adapter, { dryRun: false })).reconciled).toBe(false); });
  it("rejects malformed UUID before destination operations", async () => { const invalid: ReadOnlyBlobSource = { ...source(), async list() { return { objects: [{ ...object, key: `try-me/uploads/${id}/123e4567-e89b-02d3-a456-426614174000.pdf`, size: 1 }] }; }, async read() { return (async function* () { yield enc.encode("x"); })(); } }; await expect(migrateBlobSnapshot(invalid, destination().adapter)).rejects.toThrow("unsupported_source_object"); });
});
