import { execFileSync, spawnSync } from "node:child_process";
import { mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const cli = join(process.cwd(), "scripts/try-me-blob-migration.mjs");
const id = "abcdefghijklmnopqrst";
async function fixture(value: string) { const dir = await mkdtemp(join(tmpdir(), "try-me-cli-")); const file = join(dir, "manifest.json"); await writeFile(file, value); return { dir, file }; }
describe("try-me Blob migration planning CLI", () => {
  it("accepts the exact dry-run schema and emits only hashes", async () => { const f = await fixture(JSON.stringify({ objects: [{ key: `try-me/sessions/${id}.json`, size: 2 }] })); try { const stdout = execFileSync(process.execPath, [cli, "--dry-run", "--manifest", f.file], { encoding: "utf8" }); expect(stdout).not.toContain(id); expect(JSON.parse(stdout)).toMatchObject({ mode: "dry-run", objects: 1, bytes: 2 }); } finally { await rm(f.dir, { recursive: true }); } });
  it("rejects missing/duplicate flags and malformed JSON without leaking canary text", async () => { const f = await fixture("CANARY_SECRET_MANIFEST_TEXT"); try { for (const args of [[], ["--manifest", f.file], ["--dry-run", "--manifest", f.file, "--manifest", f.file]]) { const result = spawnSync(process.execPath, [cli, ...args], { encoding: "utf8" }); expect(result.status).toBe(2); expect(`${result.stdout}${result.stderr}`).not.toContain("CANARY_SECRET_MANIFEST_TEXT"); } const malformed = spawnSync(process.execPath, [cli, "--dry-run", "--manifest", f.file], { encoding: "utf8" }); expect(malformed.status).toBe(2); expect(malformed.stderr).toBe("invalid_manifest_json\n"); } finally { await rm(f.dir, { recursive: true }); } });
  it("rejects duplicate identities, overflow, malformed UUIDs, and symlink manifests", async () => { const f = await fixture(JSON.stringify({ objects: [{ key: `try-me/sessions/${id}.json`, size: 0 }, { key: `try-me/sessions/${id}.json`, size: 0 }] })); const link = join(f.dir, "manifest-link.json"); try { expect(spawnSync(process.execPath, [cli, "--dry-run", "--manifest", f.file], { encoding: "utf8" }).stderr).toBe("duplicate_manifest_identity\n"); await writeFile(f.file, JSON.stringify({ objects: [{ key: `try-me/sessions/${id}.json`, size: Number.MAX_SAFE_INTEGER }, { key: `try-me/leads/${id}.json`, size: 1 }] })); expect(spawnSync(process.execPath, [cli, "--dry-run", "--manifest", f.file], { encoding: "utf8" }).stderr).toBe("manifest_byte_overflow\n"); await writeFile(f.file, JSON.stringify({ objects: [{ key: `try-me/uploads/${id}/123e4567-e89b-02d3-a456-426614174000.pdf`, size: 1 }] })); expect(spawnSync(process.execPath, [cli, "--dry-run", "--manifest", f.file], { encoding: "utf8" }).stderr).toBe("invalid_manifest_object\n"); await symlink(f.file, link); expect(spawnSync(process.execPath, [cli, "--dry-run", "--manifest", link], { encoding: "utf8" }).stderr).toBe("invalid_manifest_file\n"); } finally { await rm(f.dir, { recursive: true }); } });
});
